name=MPU6050_Nexa
version=1.0.5
author=Nesara Thejan
maintainer=Nesara Thejan
sentence=A simple Arduino library for the MPU6050 sensor.
paragraph=Reads accelerometer, gyroscope and temperature data from the MPU6050 with calibration and unit conversion support.
category=Sensors
url=https://github.com/Nesara-Thejan/MPU6050_Nexa
architectures=avr
